apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - appscode.yaml
  - bitnami.yaml
  - harbor.yaml
  - ingress-nginx.yaml
  - jetstack.yaml
  - jfrog.yaml
  - prometheus-community.yaml
  - external-secrets.yaml
  - actions-runner-controller.yaml
  - grafana.yaml
  - hashicorp.yaml
  - cloudnative-pg.yaml