apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgresql-configmap.yaml
  - postgresql-secret.yaml
  - postgresql-pvc.yaml
  - postgresql-service.yaml
  - postgresql-deployment.yaml
  - offchain-init-sql-configmap.yaml
  - offchain-init-job.yaml