apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - test-crashloop-pod.yaml
  - test-error-logs-pod.yaml
  - test-failed-pod.yaml
  - test-failing-deployment.yaml
  - test-multi-container-pod.yaml
  - test-oom-pod.yaml