apiVersion: v1
kind: Pod
metadata:
  name: test-crashloop-pod
  namespace: falla-test
spec:
  containers:
  - name: crash-loop
    image: busybox
    command: ['sh', '-c', 'echo "Starting..."; sleep 2; echo "FATAL: Missing config file"; exit 1']
  restartPolicy: Always