apiVersion: v1
kind: Pod
metadata:
  name: test-oom-pod
  namespace: falla-test
spec:
  containers:
  - name: memory-eater
    image: polinux/stress
    command: ['stress']
    args: ['--vm', '1', '--vm-bytes', '500M', '--vm-hang', '1']
    resources:
      limits:
        memory: "256Mi"
      requests:
        memory: "128Mi"
  restartPolicy: Never