apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - release.yaml
  - ./dashboards/datasources.yaml
  - ./dashboards/container-log.yaml
  - ./dashboards/pod-failure.yaml
  - ./loki/config-yaml.yaml
  - ./loki/service.yaml
  - ./loki/deployment.yaml
  - ./fluentd-loki/serviceaccount.yaml
  - ./fluentd-loki/fluentd-clusterrole.yaml
  - ./fluentd-loki/clusterrolebinding.yaml
  - ./fluentd-loki/config.yaml
  - ./fluentd-loki/daemonset.yaml