apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./kustoms/reposources-kustomization.yaml
  # - ./kustoms/nginx-ingress-kustomization.yaml
  # - ./kustoms/prometheus-kustomization.yaml
  # - ./kustoms/postgresql-kustomization.yaml

  - ./devops/flux_repo/overlays/dev/kustoms/reposources-kustomization.yaml
  - ./devops/flux_repo/overlays/dev/kustoms/nginx-ingress-kustomization.yaml
  - ./devops/flux_repo/overlays/dev/kustoms/observabilidad-kustomization.yaml
  - ./devops/flux_repo/overlays/dev/kustoms/postgresql-kustomization.yaml



